// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Itis.DotnetExam.BLL.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20240109081952_AddMonsters")]
    partial class AddMonsters
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Itis.DotnetExam.Models.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1e92c4d-6670-4b4d-99cb-2d5ec1cda474"),
                            ArmorClass = 12,
                            AttackModifier = 2,
                            AttackPerRound = 2,
                            Damage = "1d6",
                            DamageModifier = 1,
                            HitPoints = 10,
                            Name = "Negrintuk"
                        },
                        new
                        {
                            Id = new Guid("421143b6-ab70-431c-8588-a3b9ed4a03bd"),
                            ArmorClass = 15,
                            AttackModifier = 4,
                            AttackPerRound = 1,
                            Damage = "1d8",
                            DamageModifier = 2,
                            HitPoints = 20,
                            Name = "Gikitru"
                        },
                        new
                        {
                            Id = new Guid("8f9d185c-9976-4b7c-b1d4-1cf6b5b5b6b7"),
                            ArmorClass = 10,
                            AttackModifier = 3,
                            AttackPerRound = 1,
                            Damage = "1d4",
                            DamageModifier = 0,
                            HitPoints = 8,
                            Name = "Gorulus"
                        },
                        new
                        {
                            Id = new Guid("9bd456a1-1524-4445-89d9-976008fdd8c9"),
                            ArmorClass = 18,
                            AttackModifier = 10,
                            AttackPerRound = 3,
                            Damage = "2d10",
                            DamageModifier = 5,
                            HitPoints = 100,
                            Name = "Vapodus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
